language: php

php: [5.3, 5.4, 5.5, 5.6, hhvm]

before_script:
  - composer install --prefer-source --no-interaction --no-progress
  - export PATH=./vendor/bin:$PATH

script:
  - phpspec run -f pretty --no-interaction

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'

